classdef obstacle_point < robotics.ros.Message
    %obstacle_point MATLAB implementation of turtlebot3_environment_scanner/obstacle_point
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'turtlebot3_environment_scanner/obstacle_point' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '4d16f326c2babd6e174a7295fb06ef0b' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        X
        Y
        Angle
        Distance
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Angle', 'Distance', 'X', 'Y'} % List of non-constant message properties
        ROSPropertyList = {'angle', 'distance', 'x', 'y'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = obstacle_point(msg)
            %obstacle_point Construct the message object obstacle_point
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function x = get.X(obj)
            %get.X Get the value for property X
            x = double(obj.JavaMessage.getX);
        end
        
        function set.X(obj, x)
            %set.X Set the value for property X
            validateattributes(x, {'numeric'}, {'nonempty', 'scalar'}, 'obstacle_point', 'X');
            
            obj.JavaMessage.setX(x);
        end
        
        function y = get.Y(obj)
            %get.Y Get the value for property Y
            y = double(obj.JavaMessage.getY);
        end
        
        function set.Y(obj, y)
            %set.Y Set the value for property Y
            validateattributes(y, {'numeric'}, {'nonempty', 'scalar'}, 'obstacle_point', 'Y');
            
            obj.JavaMessage.setY(y);
        end
        
        function angle = get.Angle(obj)
            %get.Angle Get the value for property Angle
            angle = single(obj.JavaMessage.getAngle);
        end
        
        function set.Angle(obj, angle)
            %set.Angle Set the value for property Angle
            validateattributes(angle, {'numeric'}, {'nonempty', 'scalar'}, 'obstacle_point', 'Angle');
            
            obj.JavaMessage.setAngle(angle);
        end
        
        function distance = get.Distance(obj)
            %get.Distance Get the value for property Distance
            distance = single(obj.JavaMessage.getDistance);
        end
        
        function set.Distance(obj, distance)
            %set.Distance Set the value for property Distance
            validateattributes(distance, {'numeric'}, {'nonempty', 'scalar'}, 'obstacle_point', 'Distance');
            
            obj.JavaMessage.setDistance(distance);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.X = obj.X;
            cpObj.Y = obj.Y;
            cpObj.Angle = obj.Angle;
            cpObj.Distance = obj.Distance;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.X = strObj.X;
            obj.Y = strObj.Y;
            obj.Angle = strObj.Angle;
            obj.Distance = strObj.Distance;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.X = obj.X;
            strObj.Y = obj.Y;
            strObj.Angle = obj.Angle;
            strObj.Distance = obj.Distance;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.turtlebot3_environment_scanner.obstacle_point.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.turtlebot3_environment_scanner.obstacle_point;
            obj.reload(strObj);
        end
    end
end
